### PR TITLE
Honor playState when set in initial props

### PR DESCRIPTION
**Pull request by nevir**
This allows effects to begin in a paused state, etc

### CODE REVIEW

**Comment by nevir** [comment]
Oh, I need to do this on `<Animation>` too

**Comment by bringking** [comment]
Yeah sorry, I have been meaning to come up with an interface or base class that shares this common behavior between groups, sequences and basic Animations..

**Comment by nevir** [comment]
Yeah, no worries - I've got a patch on the way; currently just doing a simple mixin.  Hopefully it fits into how you were thinking about organizing it

**Comment by nevir** [comment]
Better PR: https://github.com/RinconStrategies/react-web-animation/pull/6

**Pull request closed without merging**
